### ISSUE TITLE
FPGA ID?

### ISSUE THREAD

**Issue by samdowrick** [jankae/Signalgenerator#1]
Which FPGA did you use  as the part number given "6SLX9TQG144" doesn't exist. Im assuming its a spartan 6?

**Comment by jankae** [comment]
Yes, it is a spartan6: XC6SLX9 in the TQFP100 package

**Comment by samdowrick** [comment]
Awesome! Is the bit stream for this uploaded through the stm32 or through a jtag dongle?

**Comment by jankae** [comment]
You need to use JTAG. I didn't connect the configuration pins of the FPGA to the STM32 in this project.
